TARGET=bit_flipping.o

all:
	/home/alberto/Desktop/os/buildroot/output/host/bin/riscv64-buildroot-linux-gnu-gcc bit_flipping.c crypto_functions.h crypto_functions.c -o $(TARGET)
clean:
	rm $(TARGET)
