TARGET=test_program.o

all:
	/home/alberto/Desktop/os/buildroot/output/host/bin/riscv64-buildroot-linux-gnu-gcc test_program.c crypto_functions.c crypto_functions.h -o $(TARGET)
clean:
	rm $(TARGET)
